### ISSUE TITLE
학습코드 실행시 AttributeError가 뜹니다.

### ISSUE THREAD

**Issue by yjs1128yy** [wlsdml1114/diff-svc#38]
spk_cond_steps: [], stop_token_weight: 5.0, task_cls: training.task.SVC_task.SVCTask, test_ids: [], test_input_dir: ,
test_num: 0, test_prefixes: ['test'], test_set_name: test, timesteps: 1000, train_set_name: train,
use_amp: True, use_crepe: True, use_denoise: False, use_energy_embed: False, use_gt_dur: False,
use_gt_f0: False, use_midi: False, use_nsf: True, use_pitch_embed: True, use_pos_embed: True,
use_spk_embed: False, use_spk_id: False, use_split_spk_id: False, use_uv: False, use_var_enc: False,
use_vec: False, val_check_interval: 2000, valid_num: 0, valid_set_name: valid, validate: False,
vocoder: network.vocoders.nsf_hifigan.NsfHifiGAN, vocoder_ckpt: checkpoints/nsf_hifigan/model, warmup_updates: 2000, wav2spec_eps: 1e-6, weight_decay: 0,
win_size: 2048, work_dir: checkpoints/test,
| Mel losses: {'ssim': 0.5, 'l1': 0.5}
Error: HifiGAN model file is not found!
04/09 01:57:25 AM gpu available: True, used: True
| model Trainable Parameters: 33.709M
sample time step: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 63.23it/s]
Traceback (most recent call last):████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████         | 95/100 [00:01<00:00, 66.55it/s]
  File "C:\Users\yjs11\program\Diff_svc\diff-svc-main\run.py", line 15, in <module>
    run_task()
  File "C:\Users\yjs11\program\Diff_svc\diff-svc-main\run.py", line 11, in run_task
    task_cls.start()
  File "C:\Users\yjs11\program\Diff_svc\diff-svc-main\training\task\base_task.py", line 236, in start
    trainer.fit(task)
  File "C:\Users\yjs11\program\Diff_svc\diff-svc-main\utils\pl_utils.py", line 500, in fit
    self.run_pretrain_routine(model)
  File "C:\Users\yjs11\program\Diff_svc\diff-svc-main\utils\pl_utils.py", line 576, in run_pretrain_routine
    self.evaluate(model, self.get_val_dataloaders(), self.num_sanity_val_steps, self.testing)
  File "C:\Users\yjs11\program\Diff_svc\diff-svc-main\utils\pl_utils.py", line 1197, in evaluate
    output = self.evaluation_forward(model,
  File "C:\Users\yjs11\program\Diff_svc\diff-svc-main\utils\pl_utils.py", line 1321, in evaluation_forward
    output = model.validation_step(*args)
  File "C:\Users\yjs11\program\Diff_svc\diff-svc-main\training\task\SVC_task.py", line 159, in validation_step
    self.plot_wav(batch_idx, sample['mels'], model_out['mel_out'], is_mel=True, gt_f0=gt_f0, f0=pred_f0)
  File "C:\Users\yjs11\program\Diff_svc\diff-svc-main\training\task\SVC_task.py", line 222, in plot_wav
    gt_wav = self.vocoder.spec2wav(gt_wav, f0=gt_f0)
  File "C:\Users\yjs11\program\Diff_svc\diff-svc-main\network\vocoders\nsf_hifigan.py", line 48, in spec2wav
    if self.h.sampling_rate != hparams['audio_sample_rate']:
AttributeError: 'NsfHifiGAN' object has no attribute 'h'

python run.py --config training/config_nsf.yaml --exp_name test --reset 코드 실행 시 이런 에러가 뜹니다

**Comment by popop098** [comment]
![image](https://user-images.githubusercontent.com/53284350/230749495-2b773459-d4c1-4865-90b5-887291f29f29.png)
`Error: HifiGAN model file is not found!` 에러를 보니 전용 checkpoint를 설치하지않으신듯합니다.

**Comment by JuheonOh** [comment]
저도 삽질하다가 구글링해서 찾은결과

링크에 있는 파일(checkpoint) 다운로드하시고

config_nsf.yaml 파일 거의 밑쪽 보시면
vocoder_ckpt : checkpoints/nsf_hifigan/model
이렇게 되어있을거에요.

vocoder_ckpt 에 써진것처럼 경로 똑같이 맞춰주세요

diff-svc-main\checkpoints\nsf_hifigan

이렇게만 폴더 만드시고

그 안에 압축풀어서 나온 파일들 넣으시면 돼요

nsf_hifigan 폴더 안에는

config.json
model
NOTICE.txt
NOTICE.zh-CN.txt

파일들이 있겠죵?

**Comment by yjs1128yy** [comment]
> 

해결됬습니다. 감사합니다.
