### ISSUE TITLE
결과물 출력 오류

### ISSUE THREAD

**Issue by kohyoonchan** [wlsdml1114/diff-svc#48]
(diff-svc) C:\Users\kyc\Downloads\diff-svc-main\diff-svc-main>python infer.py
| load 'model' from './checkpoints/test/model_ckpt_steps_192000.ckpt'.
| load 'model' from 'checkpoints/0102_xiaoma_pe/model_ckpt_steps_60000.ckpt'.
| load HifiGAN:  checkpoints/0109_hifigan_bigpopcs_hop128\model_ckpt_steps_1512000.ckpt
Removing weight norm...
| Loaded model parameters from checkpoints/0109_hifigan_bigpopcs_hop128\model_ckpt_steps_1512000.ckpt.
| HifiGAN device: cuda.
code version:2022-12-04
load chunks from temp
#=====segment start, 11.125s======
jump empty segment
#=====segment start, 162.94s======
executing 'get_pitch' costed 0.957s
hubert (on cpu) time used 76.80541205406189
sample time step: 100%|████████████████████████████████████████████████████████████████| 50/50 [00:21<00:00,  2.31it/s]
executing 'diff_infer' costed 23.112s
Traceback (most recent call last):
  File "C:\Users\kyc\Downloads\diff-svc-main\diff-svc-main\infer.py", line 102, in <module>
    run_clip(model, key=tran, acc=accelerate, use_crepe=False, thre=0.05, use_pe=True, use_gt_mel=False,
  File "C:\Users\kyc\Downloads\diff-svc-main\diff-svc-main\infer.py", line 59, in run_clip
    _f0_tst, _f0_pred, _audio = svc_model.infer(raw_path, key=key, acc=acc, use_pe=use_pe, use_crepe=use_crepe,
  File "C:\Users\kyc\Downloads\diff-svc-main\diff-svc-main\infer_tools\infer_tool.py", line 167, in infer
    return self.after_infer(batch, singer, in_path)
  File "C:\Users\kyc\Downloads\diff-svc-main\diff-svc-main\infer_tools\infer_tool.py", line 62, in run
    res = func(*args, **kwargs)
  File "C:\Users\kyc\Downloads\diff-svc-main\diff-svc-main\infer_tools\infer_tool.py", line 199, in after_infer
    wav_pred = self.vocoder.spec2wav(mel_pred, f0=f0_pred)
  File "C:\Users\kyc\Downloads\diff-svc-main\diff-svc-main\network\vocoders\hifigan.py", line 70, in spec2wav
    y = self.model(c, f0).view(-1)
  File "E:\anaconda3\envs\diff-svc\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\kyc\Downloads\diff-svc-main\diff-svc-main\modules\hifigan\hifigan.py", line 163, in forward
    xs += self.resblocks[i * self.num_kernels + j](x)
  File "E:\anaconda3\envs\diff-svc\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\kyc\Downloads\diff-svc-main\diff-svc-main\modules\hifigan\hifigan.py", line 57, in forward
    xt = c1(xt)
  File "E:\anaconda3\envs\diff-svc\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\anaconda3\envs\diff-svc\lib\site-packages\torch\nn\modules\conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "E:\anaconda3\envs\diff-svc\lib\site-packages\torch\nn\modules\conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1. 이렇게 오류가 나는데 뭐 때문에 나는 오류일까요?

**Comment by popop098** [comment]
혹시 덮어씌워질 보컬 음원파일이 너무 길지않은지 확인해보세요. 3분이내가 좋습니다

**Comment by kohyoonchan** [comment]
노래 길이가 4분이라서 그런가 보네요 감사합니다
