### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity가 발생합니다.

### ISSUE THREAD

**Issue by daydream752** [wlsdml1114/diff-svc#53]
(diff-svc) C:\Users\rmatj\Downloads\diff-svc-main\diff-svc-main>python preprocessing/binarize.py --config training/config.yaml 이 명령어를 실행하면 100%까진 가는데 그 이후에
Traceback (most recent call last):
  File "C:\Users\rmatj\Downloads\diff-svc-main\diff-svc-main\preprocessing\binarize.py", line 22, in <module>
    binarize()
  File "C:\Users\rmatj\Downloads\diff-svc-main\diff-svc-main\preprocessing\binarize.py", line 17, in binarize
    binarizer_cls().process()
  File "C:\Users\rmatj\Downloads\diff-svc-main\diff-svc-main\preprocessing\base_binarizer.py", line 137, in process
    self.process_data_split('train')
  File "C:\Users\rmatj\Downloads\diff-svc-main\diff-svc-main\preprocessing\base_binarizer.py", line 175, in process_data_split
    spec_max=np.max(spec_max,0)
  File "<__array_function__ internals>", line 200, in amax
  File "C:\Users\rmatj\anaconda3\envs\diff-svc\lib\site-packages\numpy\core\fromnumeric.py", line 2820, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "C:\Users\rmatj\anaconda3\envs\diff-svc\lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity가 발생합니다.
어떻게 해결 방법이 없을 까요?

**Comment by MoorDev** [comment]
무음으로 된 파일이 있는 거 같습니다.

**Comment by theif0918** [comment]
> 무음으로 된 파일이 있는 거 같습니다.

 똑같은 오류가 발생하였습니다. 무음으로 된 파일을 일일이 다 찾아봤지만 없었습니다... 왜 이럴까요?

**Comment by MoorDev** [comment]
config에서 설정한 raw_data_dir 경로에 폴더 만들고 final이나 norm폴더에 preprocess된거 복사하신거 맞죠?
이거 가끔 까먹고 그냥 바로 돌리시는 분들 있거든요.
