### ISSUE TITLE
학습이 10000스텝에서 멈춥니다.

### ISSUE THREAD

**Issue by sleepymongsil** [wlsdml1114/diff-svc#59]
Epoch 625: : 2000batch [31:38,  2.59batch/s, batch_size=10, lr=0.0004, mel=0.0152, step=9999]
==============
 Epoch 624 ended. Steps: 9999. {'total_loss': 0.033, 'mel': 0.033, 'batch_size': 9.8125, 'lr': 0.0004}
==============

Epoch 626: : 2001batch [31:51,  4.12s/batch, batch_size=10, lr=0.0004, mel=0.037, step=10000]                          Traceback (most recent call last):                                                             | 0/5 [00:00<?, ?batch/s]
  File "<string>", line 1, in <module>
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\training\task\SVC_task.py", line 7, in <module>
    from training.task.fs2 import FastSpeech2Task
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\training\task\fs2.py", line 19, in <module>
    from training.task.tts import TtsTask
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\training\task\tts.py", line 7, in <module>
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\network\vocoders\__init__.py", line 1, in <module>
    from network.vocoders import hifigan
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\network\vocoders\hifigan.py", line 13, in <module>
    from network.vocoders.pwg import PWG
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\network\vocoders\pwg.py", line 9, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\training\task\SVC_task.py", line 7, in <module>
    from training.task.fs2 import FastSpeech2Task
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\training\task\fs2.py", line 19, in <module>
    from training.task.tts import TtsTask
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\training\task\tts.py", line 7, in <module>
    from network.vocoders.base_vocoder import get_vocoder_cls, BaseVocoder
    from modules.parallel_wavegan.utils import read_hdf5
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\network\vocoders\__init__.py", line 1, in <module>
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\modules\parallel_wavegan\utils\__init__.py", line 1, in <module>
    from network.vocoders import hifigan
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\network\vocoders\hifigan.py", line 13, in <module>
    from network.vocoders.pwg import PWG
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\network\vocoders\pwg.py", line 9, in <module>
    from modules.parallel_wavegan.utils import read_hdf5
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\modules\parallel_wavegan\utils\__init__.py", line 1, in <module>
    from .utils import *  # NOQA
    from .utils import *  # NOQA
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\modules\parallel_wavegan\utils\utils.py", line 13, in <module>
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\modules\parallel_wavegan\utils\utils.py", line 13, in <module>
    import h5py
    import h5py
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\h5py\__init__.py", line 45, in <module>
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\h5py\__init__.py", line 25, in <module>
    from ._conv import register_converters as _register_converters, \
ImportError: DLL load failed while importing _conv: 이 작업을 완료하기 위한 페이징 파일이 너무 작습니다.
    from . import _errors
ImportError: DLL load failed while importing _errors: 이 작업을 완료하기 위한 페이징 파일이 너무 작습니다.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\training\task\SVC_task.py", line 7, in <module>
    from training.task.fs2 import FastSpeech2Task
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\training\task\fs2.py", line 10, in <module>
    from utils.pl_utils import data_loader
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\utils\pl_utils.py", line 12, in <module>
    from pytorch_lightning.callbacks import GradientAccumulationScheduler
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\pytorch_lightning\__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 29, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\pytorch_lightning\callbacks\pruning.py", line 28, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\pytorch_lightning\core\__init__.py", line 16, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\pytorch_lightning\core\module.py", line 63, in <module>    from pytorch_lightning.trainer import call
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\pytorch_lightning\trainer\__init__.py", line 17, in <module>
    from pytorch_lightning.trainer.trainer import Trainer
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 43, in <module>
    from pytorch_lightning.loops import _PredictionLoop, _TrainingEpochLoop
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\pytorch_lightning\loops\__init__.py", line 15, in <module>
    from pytorch_lightning.loops.evaluation_loop import _EvaluationLoop  # noqa: F401
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\pytorch_lightning\loops\evaluation_loop.py", line 29, in <module>
    from pytorch_lightning.loops.utilities import _no_grad_context, _select_data_fetcher, _verify_dataloader_idx_requirement
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\pytorch_lightning\loops\utilities.py", line 30, in <module>
    from pytorch_lightning.strategies import FSDPStrategy
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\pytorch_lightning\strategies\__init__.py", line 15, in <module>
    from pytorch_lightning.strategies.ddp import DDPStrategy  # noqa: F401
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\pytorch_lightning\strategies\ddp.py", line 43, in <module>
    from pytorch_lightning.plugins.precision import PrecisionPlugin
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\pytorch_lightning\plugins\__init__.py", line 7, in <module>
    from pytorch_lightning.plugins.precision.amp import MixedPrecisionPlugin
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\pytorch_lightning\plugins\precision\__init__.py", line 17, in <module>
    from pytorch_lightning.plugins.precision.fsdp import FSDPMixedPrecisionPlugin
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\pytorch_lightning\plugins\precision\fsdp.py", line 23, in <module>
    from torch.distributed.fsdp.fully_sharded_data_parallel import MixedPrecision
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\torch\distributed\fsdp\__init__.py", line 2, in <module>
    from .fully_sharded_data_parallel import (
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 941, in get_code
  File "<frozen importlib._bootstrap_external>", line 1040, in get_data
MemoryError
Traceback (most recent call last):
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\torch\utils\data\dataloader.py", line 1120, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\multiprocessing\queues.py", line 114, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\run.py", line 15, in <module>
    run_task()
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\run.py", line 11, in run_task
    task_cls.start()
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\training\task\base_task.py", line 236, in start
    trainer.fit(task)
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\utils\pl_utils.py", line 500, in fit
    self.run_pretrain_routine(model)
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\utils\pl_utils.py", line 593, in run_pretrain_routine
    self.train()
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\utils\pl_utils.py", line 1369, in train
    self.run_training_epoch()
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\utils\pl_utils.py", line 1417, in run_training_epoch
    self.run_evaluation(test=self.testing)
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\utils\pl_utils.py", line 1257, in run_evaluation
    eval_results = self.evaluate(self.model,
  File "C:\Users\dolye\Downloads\diff-svc-main\diff-svc-main\utils\pl_utils.py", line 1185, in evaluate
    for batch_idx, batch in enumerate(dataloader):
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\torch\utils\data\dataloader.py", line 1316, in _next_data
    idx, data = self._get_data()
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\torch\utils\data\dataloader.py", line 1282, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\dolye\anaconda3\envs\diff-svc\lib\site-packages\torch\utils\data\dataloader.py", line 1133, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 9172, 8260, 3948) exited unexpectedly
Epoch 626: : 2001batch [32:04,  1.04batch/s, batch_size=10, lr=0.0004, mel=0.037, step=10000]

10000스텝 진행하고 저장되는 모델은 8000스텝이고 이어서 진행했을 때에도 10000스텝에서 멈추는데 어떻게 해결해야 하나요?

**Comment by DOCHIS** [comment]
메모리 용량 부족 문제로 보입니다

현재 사용중이신 메모리를 다른 프로그램 종료 같은 방법으로 비우실 수 없는 문제시라면,
가상 메모리 설정으로 가상 메모리를 늘리시거나, 한번에 학습하는 설정 량을 바꾸셔야 할 것 같은데
이건 어떤 설정을 건들여야 할 지는 모르겠습니다 ㅠㅠ

**Comment by sleepymongsil** [comment]
한번에 학습하는 량을 줄이니까 해결되었습니다. 감사합니다.
