### ISSUE TITLE
IndexError: list index out of range (binarizer 과정오류)

### ISSUE THREAD

**Issue by kmw0410** [wlsdml1114/diff-svc#60]
RTX3050 Laptop(VRAM 4GB) 쓰고있습니다
이전 과정까진 문제없이 됐는데 바이너라이저 과정에서만 계속 인덱스오류가 뜨네요;
같은현상으로 이슈 보니깐 hubert 설치해야한다 하던데 diff-svc -> checkpoints -> hubert가 있는 상황인데도 뜹니다

```
| Binarizer:  <class 'preprocessing.SVCpre.SVCBinarizer'>
Traceback (most recent call last):
  File "C:\Users\USER\Downloads\diff-svc-main\preprocessing\binarize.py", line 22, in <module>
    binarize()
  File "C:\Users\USER\Downloads\diff-svc-main\preprocessing\binarize.py", line 17, in binarize
    binarizer_cls().process()
  File "C:\Users\USER\Downloads\diff-svc-main\preprocessing\SVCpre.py", line 29, in __init__
    super().__init__(item_attributes)
  File "C:\Users\USER\Downloads\diff-svc-main\preprocessing\base_binarizer.py", line 52, in __init__
    assert all([attr in self.item_attributes for attr in list(self.items.values())[0].keys()])
IndexError: list index out of range
```

**Comment by kmw0410** [comment]
위 오류는 영상보고 중간에 몇개 빠진거같아서 빠진거 채워졌더니 해결됐는데 **No CUDA GPUs are available** 라고 뜨면서 계속 스킵되네요..
분명 쿠다관련 설정(set CUDA_VISIBLE_DEVICES=0)에서 1번으로 해뒀는데 뭐가 문제인건가요?
옵티머스 관련 옵션이 없이 무조건 내장+외장이라 GPU1(3050 Laptop)으로 해뒀습니다

**Comment by Ren-deRing** [comment]
hubert와 다른 오류네요. nsf_hifigan을 설치하셨나요?

**Comment by kmw0410** [comment]
모델 다운로드한 디스코드에서 해결했습니다
일단 처음에 올렸던건 중간에 폴더생성 등 추가과정이 빠져서 그랬던것 같고 두번째는 GPU 환경변수 설정시 실제 작업관리자에 뜨는 GPU 번호로 해서 그런듯합니다
GPU 환경변수 설정시 기존 값에서 +1이 된다하네요;
