### ISSUE TITLE
학습 이어하는게 안됩니다(AssertionError)

### ISSUE THREAD

**Issue by kmw0410** [wlsdml1114/diff-svc#61]
오전부터 돌리고 있었는데 노트북 전원 어댑터를 모르고 잠깐 빼둔다는게 계속 빼두고 있어서 꺼져버렸는데 그 뒤로 #5 해당 이슈대로 하였는데도 불구하고 계속 아래와같은 오류가 뜹니다..

6~7시간 걸쳐서 겨우 만번 넘겼는데 처음부터 다시해야 하는건가요..?

```
| Mel losses: {'ssim': 0.5, 'l1': 0.5}
| load HifiGAN:  checkpoints/0109_hifigan_bigpopcs_hop128\model_ckpt_steps_1512000.ckpt
Removing weight norm...
| Loaded model parameters from checkpoints/0109_hifigan_bigpopcs_hop128\model_ckpt_steps_1512000.ckpt.
| HifiGAN device: cuda.
| load 'model' from 'checkpoints/(비공개)/model_ckpt_steps_12000.ckpt'.
| model Trainable Parameters: 16.827M
06/23 05:29:09 PM model and trainer restored from checkpoint: checkpoints/(비공개)\model_ckpt_steps_12000.ckpt
sample time step: 100%|██████████████████████████████████████████████████████████████| 100/100 [00:45<00:00,  2.20it/s]
sample time step: 100%|██████████████████████████████████████████████████████████████| 100/100 [00:45<00:00,  2.11it/s]
==============
 valid results: {'total_loss': 0.0298, 'mel': 0.0298}
==============

Epoch 522: : 0batch [00:00, ?batch/s]Traceback (most recent call last):
  File "C:\Users\USER\Downloads\diff-svc-main\run.py", line 15, in <module>
    run_task()
  File "C:\Users\USER\Downloads\diff-svc-main\run.py", line 11, in run_task
    task_cls.start()
  File "C:\Users\USER\Downloads\diff-svc-main\training\task\base_task.py", line 236, in start
    trainer.fit(task)
  File "C:\Users\USER\Downloads\diff-svc-main\utils\pl_utils.py", line 500, in fit
    self.run_pretrain_routine(model)
  File "C:\Users\USER\Downloads\diff-svc-main\utils\pl_utils.py", line 593, in run_pretrain_routine
    self.train()
  File "C:\Users\USER\Downloads\diff-svc-main\utils\pl_utils.py", line 1369, in train
    self.run_training_epoch()
  File "C:\Users\USER\Downloads\diff-svc-main\utils\pl_utils.py", line 1403, in run_training_epoch
    output = self.run_training_batch(batch, batch_idx)
  File "C:\Users\USER\Downloads\diff-svc-main\utils\pl_utils.py", line 1529, in run_training_batch
    loss = optimizer_closure()
  File "C:\Users\USER\Downloads\diff-svc-main\utils\pl_utils.py", line 1510, in optimizer_closure
    self.scaler.scale(closure_loss).backward()
  File "C:\Users\USER\anaconda3\envs\diffsvc\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 164, in scale
    assert outputs.is_cuda or outputs.device.type == 'xla'
AssertionError
Epoch 522: : 0batch [00:09, ?batch/s]
```

**Comment by Ren-deRing** [comment]
set cuda_visible_devices=0 입력하셨나요?
최초 실행 시뿐만 아니라 여러번 실행시에도 필요합니다.

**Comment by Ren-deRing** [comment]
그리고 GPU가 무엇인지 여쭤봐도 될까요?

**Comment by kmw0410** [comment]
노트북 3050 입니다

**Comment by kmw0410** [comment]
> 그리고 GPU가 무엇인지 여쭤봐도 될까요?

노트북 3050 사용중입니다




> set cuda_visible_devices=0 입력하셨나요? 최초 실행 시뿐만 아니라 여러번 실행시에도 필요합니다.

이전에는 여러번 실행해도 안이랬던것 같은데 원래 매번 실행할때마다 해야하는건가요? (위에 다시 쳐주니깐 정상적으로 되는것같습니다)

**Comment by Ren-deRing** [comment]
에러메시지를 보아 GPU 쪽 문제라서 그렇게 답변드렸던건데, 저도 잘 모르겠네요
