### ISSUE TITLE
binarize 중 indexError가 발생했습니다

### ISSUE THREAD

**Issue by Cherrlyy** [wlsdml1114/diff-svc#70]
| Binarizer:  <class 'preprocessing.SVCpre.SVCBinarizer'>
Traceback (most recent call last):
  File "D:\Download\diff-svc-main\diff-svc-main\preprocessing\binarize.py", line 22, in <module>
    binarize()
  File "D:\Download\diff-svc-main\diff-svc-main\preprocessing\binarize.py", line 17, in binarize
    binarizer_cls().process()
  File "D:\Download\diff-svc-main\diff-svc-main\preprocessing\..\preprocessing\SVCpre.py", line 29, in __init__
    super().__init__(item_attributes)
  File "D:\Download\diff-svc-main\diff-svc-main\preprocessing\..\preprocessing\base_binarizer.py", line 52, in __init__
    assert all([attr in self.item_attributes for attr in list(self.items.values())[0].keys()])
IndexError: list index out of range

이렇게 에러가 발생하는데, 다른 분들 이슈 따라서 재부팅 후 재설치도 해보고 hubert 위치도 체크해보고 절대경로 설정도 해봤습니다.... 도와주세요 ㅠㅠㅠ 경로 모두 영어입니다

**Comment by Cherrlyy** [comment]
config, config_nsf 전부 설정 동일하게 하면 됩니다! 해결됐습니다
