### ISSUE TITLE
python sep_wav.py 오류

### ISSUE THREAD

**Issue by fps102** [wlsdml1114/diff-svc#8]
목소리 추출 중...:   0%|                                                                        | 0/21 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\82107\Downloads\diff-svc-main\diff-svc-main\sep_wav.py", line 284, in <module>
    main(
  File "C:\Users\82107\Downloads\diff-svc-main\diff-svc-main\sep_wav.py", line 220, in main
    sources = extract_voice(
  File "C:\Users\82107\Downloads\diff-svc-main\diff-svc-main\sep_wav.py", line 61, in extract_voice
    out = model.forward(chunk)
  File "C:\Users\82107\anaconda3\envs\diff-svc\lib\site-packages\torchaudio\models\_hdemucs.py", line 539, in forward
    raise ValueError(
ValueError: The channel dimension of input Tensor must match `audio_channels` of HDemucs model. Found:1.

이렇게 뜨면서 변환이 안됩니다 ㅠㅠ

**Comment by wlsdml1114** [comment]
아 최근에 추가한 sample rate랑 channel을 맞춰주는 과정에서 생긴 오류같습니다.
sep_wav.py파일의 280번째 줄의 use_preprocessing을 False (use_preprocessing = False)를 하고 진행해보실래요?
지금당장은 수정하기가 힘드네요;;

**Comment by fps102** [comment]
답변 감사드립니다. 수정 후 진행 중에 binarize 중 python preprocessing/binarize.py --config training/config.yaml
 입력하니 ValueError: zero-size array to reduction operation maximum which has no identity 라고 오류가 뜹니다ㅠㅠ

**Comment by wlsdml1114** [comment]
혹시 에러 전체메세지를 올려주실 수 있나요
어디서 에러가 났는지를 확인해야되서요
